spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tiny_task
    username: tiny_task
    password: demo123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
